luno/luno-go

- luno.go
The Luno API now returns meaningful response codes.
> Remove error handling code for 200 responses

- api.go
- examples/readonly/main.go
- time.go
- types.go
- `Order.State` and `GetOrderResponse.State`'s type changed to `OrderState`
- `Order.Type` and `GetOrderResponse.Type`'s type changed to `OrderType`
- `Since` parameters changed from `int64`s to `Time`s
> Fix some request/response types

- README.md
The README hadn't been updated for over a year. 
Hence, the example provided does not actually work with the most recent version of the library.
I updated the README to show a full working example compatible with the most recent version of the library, which requires `Context` to be passed to the methods of `Client`.
> Updated the README to show a working example for the latest version (Closes #52)

- streaming/streaming.go
Gracefully return when the server terminates the connection instead of logging the error. This will still trigger a reconnect.
> Handle Server Connection Termination

- api.go
- util.go
- util_internal_test.go
The endpoints `GetTickers` (`/api/1/tickers`) and `GetBalances` (`/api/1/balance`) have []string parameters, which are not converted correctly and the empty string is passed to the query instead.
This fixes that, and adds the `pair` param to `GetTickers`, to be consistent with the API doc.
> Fix the conversion of []string params

- decimal/decimal.go
- decimal/decimal_test.go
Before:
```
d1, _ := decimal.NewFromString("0.17800000")
d2, _ := decimal.NewFromString("6750.00000000")
fmt.Println(d1.Mul(d2).Float64())
-643.1744073709551
```
After:
```
d1, _ := decimal.NewFromString("0.17800000")
d2, _ := decimal.NewFromString("6750.00000000")
fmt.Println(d1.Mul(d2).Float64())
1201.5
```
> Update float64() implementation to better handle decimal precision

- types.go
Please refer to the API specification: 
https://www.luno.com/en/developers/api#tag/Streaming-API
Scroll down to where this is mentioned:
```The server will then send the current order book in the following format:```
The API shows that bids and asks are accompanied by an ID. The ID is indeed included in the streamed data, but the client does not make use of the field.
This change is to make the ID field available to client users.
> Adding ID to OrderBookEntry

- streaming/messages.go
Here is some raw data returned by the webhook.  Notice that the maker and taker order ID is present in the json object, but the fields are missing in the API's `TradeUpdate` struct.  This PR makes these two fields available to client applications.
```
{
"sequence": "1441552179",
"trade_updates": [
{
"base": "0.00083400",
"counter": "443.0233020000000000",
"maker_order_id": "BXJ7CE79BHRPTVS",
"taker_order_id": "BXCMS3RWN3FJW84",
"order_id": "BXJ7CE79BHRPTVS"
}
],
"create_update": {
"order_id": "BXCMS3RWN3FJW84",
"type": "ASK",
"price": "531203.00000000",
"volume": "0.00105200"
},
"delete_update": null,
"status_update": null,
"timestamp": 1684657400681
}
```
> Adding missing maker and taker order ID fields to TradeUpdate struct

- streaming/messages.go
- streaming/streaming.go
- streaming/streaming_internal_test.go
A change was recently made to the backend API server to include the trade sequence in the TradeUpdate struct.
This PR makes the corresponding change to the go SDK.
Tests have also been updated and corrected.
> Adding Sequence to TradeUpdate in the web socket API

- streaming/streaming.go
- streaming/streaming_internal_test.go
- types.go
Reworking [Pull/96](https://github.com/luno/luno-go/pull/96/) 
ID assignment needed to be added to the flatten function.
The naming of the Id field also clashes with the naming convention of IDs in the library so renamed it to ID.
The `Id` field was added a few days ago and is not tagged in a version, so in theory it can still be renamed without being a breaking change.
> Add order id to flatten

- api.go
- decimal/decimal.go
- decimal/decimal_internal_test.go
- decimal/decimal_test.go
- errors_test.go
- luno.go
- streaming/streaming.go
- streaming/streaming_internal_test.go
- time_test.go
- util.go
- util_internal_test.go
- gofumpt runs on our precommit hooks, so running it now will avoid noise in MRs going forwards when these updates get made
> gofumpt: Run on whole repo to prevent noise going forwards

- api.go
Fixed the HTML links for SendRequest, additionally fixed the unordered list, and made the <b>Note</b> look emphasized.
I was not able to fix the HTML link in the PostMarketOrder since the full URL was not provided. We can show code blocks instead of using the 'code' tags but the code will be displayed in a new line. which would look as follows.
Addresses: https://github.com/luno/luno-go/issues/97
> Fix HTML links on godoc

- .github/workflows/test.yml
-  go version in test.yml to be 1.21
> ci: Update go version in test.yml to be 1.21

- streaming/streaming.go
- streaming/streaming_test.go
This will flatten price points so that all orders at a certain price appear with a single volume amount.
> streaming: Flatten orders in orderbook

- api.go
- streaming/streaming.go
- streaming/streaming_internal_test.go
- types.go
Add support for memo field for ATOM coin (clean up orderbookentry id that was not added using sdkgenerator)
> Add support for memo field for ATOM coin

- api.go
- types.go
- `TransferId` to:
- `CancelWithdrawalResponse`
- `CreateWithdrawalResponse`
- `GetWithdrawalResponse`
- `Withdrawal`
> api: Regenerate types - add TransferID

- streaming/streaming.go
- streaming/streaming_internal_test.go
When a market snapshot is requested by the client from within the UpdateCallback delegate, a mutex deadlock is encountered. This is caused by the write mutex not being released when UpdateCallback is called by the stream and the snapshot function trying to read lock the same mutex.
Getting the snapshot during the UpdateCallback call is useful because this enables the client to consider the full orderbook when applying trading logic.
The resolution is to first release the write mutex before calling the UpdateCallback delegate.
> Resolve deadlock caused by fetching snapshot during update

- renovate.json
- Renovate to use common config added in https://github.com/luno/.github/pull/2
> renovate: Use common config

- renovate.json
- Config name: renovate-config matches the JSON filename present at https://github.com/luno/.github/ (see [docs](https://docs.renovatebot.com/config-presets/))
- Tested with forks:
- https://github.com/echarrod/.github
- https://github.com/echarrod/luno-go
- Started to change the file name in https://github.com/luno/.github/pull/3, but thought this was better since that repo has non-renovate items in, so calling it `default.json` wouldn't indicate what it's being used for
> renovate: Correct parent config reference

- go.mod
- Following official Go stance of supporting two most recent major versions
> gomod: Update version to Go 1.21
